--------------------------------------------------------
-- Archivo creado  - sábado-junio-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRO_AFILIADO
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_AFILIADO" 
   (	"AFI_ID" NUMBER, 
	"AFI_NOMBRES" VARCHAR2(150 BYTE), 
	"AFI_APEPATERNO" VARCHAR2(50 BYTE), 
	"AFI_APEMATERNO" VARCHAR2(50 BYTE), 
	"AFI_ESTADO" CLOB DEFAULT 1, 
	"AFI_FECNAC" DATE, 
	"AFI_EDAD" NUMBER, 
	"AFI_SEXO" CHAR(1 BYTE), 
	"AFI_TELEFONO" VARCHAR2(20 BYTE), 
	"AFI_DNI" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("AFI_ESTADO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "APPPRO"."PRO_AFILIADO"."AFI_ESTADO" IS 'ESTADO AFILIADO';
--------------------------------------------------------
--  DDL for Table USER_ROLES
--------------------------------------------------------

  CREATE TABLE "APPPRO"."USER_ROLES" 
   (	"ROLE_ID" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(36 BYTE), 
	"USER_ROLE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "APPPRO"."USERS" 
   (	"USERNAME" VARCHAR2(36 BYTE), 
	"PASSWORD" VARCHAR2(36 BYTE), 
	"ESTADO" NUMBER(1,0), 
	"NOMBRES" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View W_PRO_AFILIADO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "APPPRO"."W_PRO_AFILIADO" ("AFI_ID", "AFI_NOMBRES", "AFI_APEPATERNO", "AFI_APEMATERNO", "AFI_ESTADO", "AFI_FECNAC", "AFI_EDAD", "AFI_SEXO", "AFI_TELEFONO", "AFI_DNI") AS 
  SELECT "AFI_ID","AFI_NOMBRES","AFI_APEPATERNO","AFI_APEMATERNO","AFI_ESTADO","AFI_FECNAC","AFI_EDAD","AFI_SEXO","AFI_TELEFONO","AFI_DNI"    FROM APPPRO.PRO_AFILIADO;
--------------------------------------------------------
--  DDL for View W_PRO_LOGUEO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "APPPRO"."W_PRO_LOGUEO" ("USERNAME", "PASSWORD", "USER_ROLE", "ESTADO", "NOMBRES", "APELLIDOS") AS 
  SELECT U.USERNAME,PASSWORD,USER_ROLE, ESTADO , NOMBRES ,
APELLIDOS from USERS U INNER JOIN USER_ROLES R ON U.USERNAME=R.USERNAME;
REM INSERTING into APPPRO.PRO_AFILIADO
SET DEFINE OFF;
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('1','PEPITO','LLOPEZ','CONTRERAS',to_date('01/06/13','DD/MM/RR'),'33','M','45488552','08999999');
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('2','LUISA','HERNADEZ','FERNANDEZ',to_date('01/06/13','DD/MM/RR'),'27','F','96955882','09888888');
REM INSERTING into APPPRO.USER_ROLES
SET DEFINE OFF;
Insert into APPPRO.USER_ROLES (ROLE_ID,USERNAME,USER_ROLE) values ('2','dbadmin1','ADMINISTRADOR');
Insert into APPPRO.USER_ROLES (ROLE_ID,USERNAME,USER_ROLE) values ('3','dbuser2','USUARIO');
Insert into APPPRO.USER_ROLES (ROLE_ID,USERNAME,USER_ROLE) values ('1','dbuser1','USUARIO');
REM INSERTING into APPPRO.USERS
SET DEFINE OFF;
Insert into APPPRO.USERS (USERNAME,PASSWORD,ESTADO,NOMBRES,APELLIDOS) values ('dbuser1','12345','1','JUAN','MINCHOLA');
Insert into APPPRO.USERS (USERNAME,PASSWORD,ESTADO,NOMBRES,APELLIDOS) values ('dbadmin1','12345','1','PATRICIA','CORONADO');
--------------------------------------------------------
--  DDL for Index USER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."USER_ROLE_PK" ON "APPPRO"."USER_ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."USER_PK" ON "APPPRO"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRO_AFILIADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."PRO_AFILIADO_PK" ON "APPPRO"."PRO_AFILIADO" ("AFI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_ROLE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."USER_ROLE_UK" ON "APPPRO"."USER_ROLES" ("USERNAME", "USER_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRO_AFILIADO
--------------------------------------------------------

  ALTER TABLE "APPPRO"."PRO_AFILIADO" ADD CONSTRAINT "PRO_AFILIADO_PK" PRIMARY KEY ("AFI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPPRO"."PRO_AFILIADO" MODIFY ("AFI_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "APPPRO"."USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USER_ROLES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USER_ROLES" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USER_ROLES" ADD CONSTRAINT "USER_ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPPRO"."USER_ROLES" ADD CONSTRAINT "USER_ROLE_UK" UNIQUE ("USERNAME", "USER_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "APPPRO"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USERS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USERS" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
